// <auto-generated />
namespace DL.Migrations.Blog
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class exercise_modify : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(exercise_modify));
        
        string IMigrationMetadata.Id
        {
            get { return "201805201445072_exercise_modify"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
